// Package x64 provides x86-64 code generation from AST
package x64

import (
	"fmt"
	"goc/parser"
	"goc/semantic"
	"goc/types"
	"runtime"
)

// CallingConvention represents the function calling convention
type CallingConvention int

const (
	// WindowsX64 uses RCX, RDX, R8, R9 for first 4 parameters
	WindowsX64 CallingConvention = iota
	// SystemVAMD64 uses RDI, RSI, RDX, RCX, R8, R9 for first 6 parameters (Linux/macOS)
	SystemVAMD64
)

// CodeGenerator generates x86-64 assembly code from AST
type CodeGenerator struct {
	asm       *Assembler             // Assembly code builder
	analyzer  *semantic.Analyzer     // Semantic analyzer for type info
	convention CallingConvention      // Calling convention to use

	// Function-level state
	stackOffset int64                // Current stack offset (bytes from RBP)
	varOffsets  map[string]int64     // Variable name -> stack offset map
	labelCount  int                  // Counter for generating unique labels
}

// NewCodeGenerator creates a new x86-64 code generator
func NewCodeGenerator(analyzer *semantic.Analyzer) *CodeGenerator {
	// Determine calling convention based on OS
	convention := SystemVAMD64
	if runtime.GOOS == "windows" {
		convention = WindowsX64
	}

	return &CodeGenerator{
		asm:        NewAssembler(),
		analyzer:   analyzer,
		convention: convention,
		varOffsets: make(map[string]int64),
	}
}

// Generate generates x86-64 assembly code from AST
func (cg *CodeGenerator) Generate(program *parser.Program) error {
	// Emit file header comment
	cg.asm.EmitComment("Generated by GoC Compiler - x86-64 backend")
	cg.asm.EmitComment(fmt.Sprintf("Target: %s", runtime.GOOS))
	cg.asm.EmitComment("")

	// Generate code for all functions
	for _, fn := range program.Functions {
		if err := cg.generateFunction(fn); err != nil {
			return err
		}
	}

	return nil
}

// generateFunction generates code for a function
func (cg *CodeGenerator) generateFunction(fn *parser.FunctionDecl) error {
	// Reset function-level state
	cg.stackOffset = 0
	cg.varOffsets = make(map[string]int64)
	cg.labelCount = 0

	cg.asm.EmitComment(fmt.Sprintf("Function: %s", fn.Name))

	// Emit function label (globally visible)
	if fn.Name == "main" {
		// Make main globally visible as entry point
		cg.asm.EmitLabel("_start") // Entry point for ELF
		cg.asm.EmitLabel("main")   // Also emit "main" for compatibility
	} else {
		cg.asm.EmitLabel(fn.Name)
	}

	// Function prologue
	cg.generatePrologue()

	// Allocate stack space for parameters
	if err := cg.allocateParameters(fn.Parameters); err != nil {
		return err
	}

	// Generate code for function body
	if err := cg.generateBlock(fn.Body); err != nil {
		return err
	}

	// Function epilogue (in case there's no explicit return)
	cg.generateEpilogue()

	cg.asm.EmitComment("")
	return nil
}

// generatePrologue generates function prologue
func (cg *CodeGenerator) generatePrologue() {
	// Standard x86-64 function prologue
	cg.asm.Push(RegOperand{Reg: RBP})           // Save old base pointer
	cg.asm.Mov(RegOperand{Reg: RBP}, RegOperand{Reg: RSP}) // Set new base pointer

	// Reserve stack space for local variables
	// We'll adjust this later when we know the total size needed
	// For now, reserve a reasonable amount (256 bytes)
	cg.asm.Sub(RegOperand{Reg: RSP}, ImmOperand{Value: 256})
}

// generateEpilogue generates function epilogue
func (cg *CodeGenerator) generateEpilogue() {
	// Standard x86-64 function epilogue
	cg.asm.Mov(RegOperand{Reg: RSP}, RegOperand{Reg: RBP}) // Restore stack pointer
	cg.asm.Pop(RegOperand{Reg: RBP})                       // Restore base pointer
	cg.asm.Ret()                                           // Return
}

// allocateParameters allocates stack space for function parameters
func (cg *CodeGenerator) allocateParameters(params []*parser.Parameter) error {
	// Get parameter registers based on calling convention
	paramRegs := cg.getParamRegisters()

	for i, param := range params {
		// Allocate stack space for this parameter
		cg.stackOffset -= 8 // Each parameter takes 8 bytes (even 32-bit values)
		cg.varOffsets[param.Name] = cg.stackOffset

		// Move parameter from register to stack
		if i < len(paramRegs) {
			// Parameter is in register
			paramType := types.FromString(param.Type)
			if paramType.Equals(types.FloatType) {
				// Float parameter comes in XMM register
				xmmReg := XMM0 + Register(i)
				cg.asm.Movss(MemOperand{Base: RBP, Offset: cg.stackOffset}, RegOperand{Reg: xmmReg})
			} else {
				// Integer parameter comes in general-purpose register
				// Need to use 32-bit register for int
				reg := paramRegs[i]
				cg.asm.Mov(MemOperand{Base: RBP, Offset: cg.stackOffset}, RegOperand{Reg: reg})
			}
		} else {
			// Parameter is on stack (passed by caller)
			// Skip for now - would be at [rbp + 16 + i*8]
			return fmt.Errorf("too many parameters (only %d supported)", len(paramRegs))
		}
	}

	return nil
}

// getParamRegisters returns the parameter registers based on calling convention
func (cg *CodeGenerator) getParamRegisters() []Register {
	if cg.convention == WindowsX64 {
		return []Register{RCX, RDX, R8, R9}
	}
	return []Register{RDI, RSI, RDX, RCX, R8, R9}
}

// generateBlock generates code for a block statement
func (cg *CodeGenerator) generateBlock(block *parser.BlockStmt) error {
	for _, stmt := range block.Statements {
		if err := cg.generateStatement(stmt); err != nil {
			return err
		}
	}
	return nil
}

// generateStatement generates code for a statement
func (cg *CodeGenerator) generateStatement(stmt parser.Statement) error {
	switch s := stmt.(type) {
	case *parser.VarDeclStmt:
		return cg.generateVarDecl(s)
	case *parser.AssignStmt:
		return cg.generateAssignment(s)
	case *parser.ReturnStmt:
		return cg.generateReturn(s)
	case *parser.IfStmt:
		return cg.generateIf(s)
	case *parser.WhileStmt:
		return cg.generateWhile(s)
	case *parser.ExprStmt:
		return cg.generateExprStmt(s)
	case *parser.BlockStmt:
		return cg.generateBlock(s)
	default:
		return fmt.Errorf("unknown statement type: %T", stmt)
	}
}

// generateVarDecl generates code for variable declaration
func (cg *CodeGenerator) generateVarDecl(decl *parser.VarDeclStmt) error {
	// Allocate stack space for variable
	cg.stackOffset -= 8 // Each variable takes 8 bytes
	cg.varOffsets[decl.Name] = cg.stackOffset

	// If there's an initializer, generate code for it
	if decl.Value != nil {
		// Get variable type (either explicit or inferred from expression)
		var varType types.Type
		if decl.Type != "" {
			// Explicit type declaration
			varType = types.FromString(decl.Type)
		} else {
			// Type inference from expression
			varType = cg.analyzer.GetExprType(decl.Value)
		}

		if err := cg.generateExpression(decl.Value, varType); err != nil {
			return err
		}

		// Store result to variable's stack location
		if varType.Equals(types.FloatType) {
			// Result is in XMM0
			cg.asm.Movss(MemOperand{Base: RBP, Offset: cg.stackOffset}, RegOperand{Reg: XMM0})
		} else {
			// Result is in RAX
			cg.asm.Mov(MemOperand{Base: RBP, Offset: cg.stackOffset}, RegOperand{Reg: EAX})
		}
	}

	return nil
}

// generateAssignment generates code for assignment statement
func (cg *CodeGenerator) generateAssignment(assign *parser.AssignStmt) error {
	// Get the type from the value expression (this works for both first assignment and reassignment)
	varType := cg.analyzer.GetExprType(assign.Value)
	if varType == nil {
		return fmt.Errorf("cannot determine type for variable: %s", assign.Name)
	}

	// Generate code for right-hand side
	if err := cg.generateExpression(assign.Value, varType); err != nil {
		return err
	}

	// Check if variable already has stack space allocated
	offset, ok := cg.varOffsets[assign.Name]
	if !ok {
		// This is a first assignment (type-inferred declaration)
		// Allocate stack space
		cg.stackOffset -= 8
		offset = cg.stackOffset
		cg.varOffsets[assign.Name] = offset
	}

	// Store result to variable's stack location
	if varType.Equals(types.FloatType) {
		cg.asm.Movss(MemOperand{Base: RBP, Offset: offset}, RegOperand{Reg: XMM0})
	} else {
		cg.asm.Mov(MemOperand{Base: RBP, Offset: offset}, RegOperand{Reg: EAX})
	}

	return nil
}

// generateReturn generates code for return statement
func (cg *CodeGenerator) generateReturn(ret *parser.ReturnStmt) error {
	// Generate code for return value
	// The result should be in RAX (for int) or XMM0 (for float)
	if ret.Value != nil {
		exprType := cg.analyzer.GetExprType(ret.Value)
		if err := cg.generateExpression(ret.Value, exprType); err != nil {
			return err
		}
	}

	// Generate epilogue and return
	cg.generateEpilogue()

	return nil
}

// generateExprStmt generates code for expression statement
func (cg *CodeGenerator) generateExprStmt(stmt *parser.ExprStmt) error {
	exprType := cg.analyzer.GetExprType(stmt.Expression)
	return cg.generateExpression(stmt.Expression, exprType)
}

// generateIf generates code for if statement
func (cg *CodeGenerator) generateIf(ifStmt *parser.IfStmt) error {
	// Generate unique labels
	elseLabel := cg.newLabel("else")
	endLabel := cg.newLabel("endif")

	// Generate condition
	condType := cg.analyzer.GetExprType(ifStmt.Condition)
	if err := cg.generateExpression(ifStmt.Condition, condType); err != nil {
		return err
	}

	// Test result and jump
	if condType.Equals(types.FloatType) {
		// Float comparison: compare with 0.0
		cg.asm.EmitComment("Compare float with zero")
		cg.asm.Xor(RegOperand{Reg: EAX}, RegOperand{Reg: EAX})
		cg.asm.Cvtsi2ss(RegOperand{Reg: XMM1}, RegOperand{Reg: EAX})
		cg.asm.Ucomiss(RegOperand{Reg: XMM0}, RegOperand{Reg: XMM1})
		if ifStmt.ElseBranch != nil {
			cg.asm.Je(elseLabel)
		} else {
			cg.asm.Je(endLabel)
		}
	} else {
		// Integer comparison
		cg.asm.Test(RegOperand{Reg: EAX}, RegOperand{Reg: EAX})
		if ifStmt.ElseBranch != nil {
			cg.asm.Je(elseLabel)
		} else {
			cg.asm.Je(endLabel)
		}
	}

	// Generate then branch
	if err := cg.generateBlock(ifStmt.ThenBranch); err != nil {
		return err
	}

	// If there's an else branch
	if ifStmt.ElseBranch != nil {
		cg.asm.Jmp(endLabel)
		cg.asm.EmitLabel(elseLabel)
		if err := cg.generateBlock(ifStmt.ElseBranch); err != nil {
			return err
		}
	}

	cg.asm.EmitLabel(endLabel)
	return nil
}

// generateWhile generates code for while loop
func (cg *CodeGenerator) generateWhile(whileStmt *parser.WhileStmt) error {
	// Generate unique labels
	condLabel := cg.newLabel("while_cond")
	endLabel := cg.newLabel("while_end")

	// Loop condition
	cg.asm.EmitLabel(condLabel)

	condType := cg.analyzer.GetExprType(whileStmt.Condition)
	if err := cg.generateExpression(whileStmt.Condition, condType); err != nil {
		return err
	}

	// Test condition
	if condType.Equals(types.FloatType) {
		cg.asm.Xor(RegOperand{Reg: EAX}, RegOperand{Reg: EAX})
		cg.asm.Cvtsi2ss(RegOperand{Reg: XMM1}, RegOperand{Reg: EAX})
		cg.asm.Ucomiss(RegOperand{Reg: XMM0}, RegOperand{Reg: XMM1})
		cg.asm.Je(endLabel)
	} else {
		cg.asm.Test(RegOperand{Reg: EAX}, RegOperand{Reg: EAX})
		cg.asm.Je(endLabel)
	}

	// Loop body
	if err := cg.generateBlock(whileStmt.Body); err != nil {
		return err
	}

	// Jump back to condition
	cg.asm.Jmp(condLabel)

	cg.asm.EmitLabel(endLabel)
	return nil
}

// newLabel generates a unique label
func (cg *CodeGenerator) newLabel(prefix string) string {
	cg.labelCount++
	return fmt.Sprintf(".L%s_%d", prefix, cg.labelCount)
}

// GetAssembler returns the assembler instance
func (cg *CodeGenerator) GetAssembler() *Assembler {
	return cg.asm
}

// GetAssembly returns the generated assembly code as a slice of instructions
func (cg *CodeGenerator) GetAssembly() []interface{} {
	return cg.asm.Code
}

// GetAssemblyString returns the generated assembly code as a string
func (cg *CodeGenerator) GetAssemblyString() string {
	result := ""
	for _, code := range cg.asm.Code {
		switch c := code.(type) {
		case Instruction:
			result += "    " + c.String() + "\n"
		case Label:
			result += c.String() + "\n"
		case Comment:
			result += c.String() + "\n"
		case Section:
			result += c.String() + "\n"
		}
	}
	return result
}

// ========== Expression Generation ==========

// generateExpression generates code for an expression
// Result is left in RAX (for int) or XMM0 (for float)
func (cg *CodeGenerator) generateExpression(expr parser.Expression, expectedType types.Type) error {
	switch e := expr.(type) {
	case *parser.IntLiteral:
		return cg.generateIntLiteral(e)
	case *parser.FloatLiteral:
		return cg.generateFloatLiteral(e)
	case *parser.Identifier:
		return cg.generateIdentifier(e, expectedType)
	case *parser.BinaryExpr:
		return cg.generateBinaryExpr(e)
	case *parser.UnaryExpr:
		return cg.generateUnaryExpr(e)
	case *parser.CallExpr:
		return cg.generateCallExpr(e)
	default:
		return fmt.Errorf("unknown expression type: %T", expr)
	}
}

// generateIntLiteral generates code for integer literal
func (cg *CodeGenerator) generateIntLiteral(lit *parser.IntLiteral) error {
	// Load immediate value into EAX
	cg.asm.Mov(RegOperand{Reg: EAX}, ImmOperand{Value: lit.Value})
	return nil
}

// generateFloatLiteral generates code for float literal
func (cg *CodeGenerator) generateFloatLiteral(lit *parser.FloatLiteral) error {
	// For simplicity, we'll convert float to int, then int to float
	// In a real compiler, we'd store the float in .data section and load it
	intValue := int64(lit.Value)
	cg.asm.Mov(RegOperand{Reg: EAX}, ImmOperand{Value: intValue})
	cg.asm.Cvtsi2ss(RegOperand{Reg: XMM0}, RegOperand{Reg: EAX})
	return nil
}

// generateIdentifier generates code for identifier (variable reference)
func (cg *CodeGenerator) generateIdentifier(ident *parser.Identifier, varType types.Type) error {
	offset, ok := cg.varOffsets[ident.Name]
	if !ok {
		return fmt.Errorf("undefined variable: %s", ident.Name)
	}

	// Load variable from stack
	if varType.Equals(types.FloatType) {
		cg.asm.Movss(RegOperand{Reg: XMM0}, MemOperand{Base: RBP, Offset: offset})
	} else {
		cg.asm.Mov(RegOperand{Reg: EAX}, MemOperand{Base: RBP, Offset: offset})
	}

	return nil
}

// generateBinaryExpr generates code for binary expression
func (cg *CodeGenerator) generateBinaryExpr(expr *parser.BinaryExpr) error {
	// Get operand types
	leftType := cg.analyzer.GetExprType(expr.Left)
	rightType := cg.analyzer.GetExprType(expr.Right)

	// Determine if we're doing float or int arithmetic
	isFloat := leftType.Equals(types.FloatType)

	// Generate code for left operand
	if err := cg.generateExpression(expr.Left, leftType); err != nil {
		return err
	}

	// Save left operand result
	if isFloat {
		// Push XMM0 to stack (need to use memory)
		cg.asm.Sub(RegOperand{Reg: RSP}, ImmOperand{Value: 8})
		cg.asm.Movss(MemOperand{Base: RSP, Offset: 0}, RegOperand{Reg: XMM0})
	} else {
		cg.asm.Push(RegOperand{Reg: RAX})
	}

	// Generate code for right operand
	if err := cg.generateExpression(expr.Right, rightType); err != nil {
		return err
	}

	// Restore left operand
	if isFloat {
		// Pop left operand into XMM1
		cg.asm.Movss(RegOperand{Reg: XMM1}, MemOperand{Base: RSP, Offset: 0})
		cg.asm.Add(RegOperand{Reg: RSP}, ImmOperand{Value: 8})
		// Now: XMM1 = left, XMM0 = right
	} else {
		// Pop left operand into RBX
		cg.asm.Pop(RegOperand{Reg: RBX})
		// Now: RBX = left, RAX = right
	}

	// Perform operation
	if isFloat {
		return cg.generateFloatBinaryOp(expr.Operator)
	}
	return cg.generateIntBinaryOp(expr.Operator)
}

// generateIntBinaryOp generates code for integer binary operations
// Assumes: RBX = left operand, RAX = right operand
// Result in RAX
func (cg *CodeGenerator) generateIntBinaryOp(op string) error {
	switch op {
	case "+":
		cg.asm.Add(RegOperand{Reg: RAX}, RegOperand{Reg: RBX})
	case "-":
		// RAX = RBX - RAX
		cg.asm.Mov(RegOperand{Reg: RCX}, RegOperand{Reg: RBX})
		cg.asm.Sub(RegOperand{Reg: RCX}, RegOperand{Reg: RAX})
		cg.asm.Mov(RegOperand{Reg: RAX}, RegOperand{Reg: RCX})
	case "*":
		cg.asm.Imul(RegOperand{Reg: RAX}, RegOperand{Reg: RBX})
	case "/":
		// Signed division: RAX = RBX / RAX
		cg.asm.Mov(RegOperand{Reg: RAX}, RegOperand{Reg: RBX})
		cg.asm.Cqo() // Sign extend RAX to RDX:RAX
		cg.asm.Mov(RegOperand{Reg: RBX}, MemOperand{Base: RSP, Offset: -8}) // Get divisor
		cg.asm.Idiv(RegOperand{Reg: RBX})
	case "%":
		// Modulo: RDX = RBX % RAX
		cg.asm.Mov(RegOperand{Reg: RAX}, RegOperand{Reg: RBX})
		cg.asm.Cqo()
		cg.asm.Mov(RegOperand{Reg: RBX}, MemOperand{Base: RSP, Offset: -8})
		cg.asm.Idiv(RegOperand{Reg: RBX})
		cg.asm.Mov(RegOperand{Reg: RAX}, RegOperand{Reg: RDX}) // Move remainder to RAX
	case "==":
		cg.asm.Cmp(RegOperand{Reg: RBX}, RegOperand{Reg: RAX})
		cg.asm.Sete(RegOperand{Reg: AL}) // AL is the low byte of RAX
		cg.asm.Movzx(RegOperand{Reg: EAX}, RegOperand{Reg: AL})
	case "!=":
		cg.asm.Cmp(RegOperand{Reg: RBX}, RegOperand{Reg: RAX})
		cg.asm.Setne(RegOperand{Reg: AL})
		cg.asm.Movzx(RegOperand{Reg: EAX}, RegOperand{Reg: AL})
	case "<":
		cg.asm.Cmp(RegOperand{Reg: RBX}, RegOperand{Reg: RAX})
		cg.asm.Setl(RegOperand{Reg: AL})
		cg.asm.Movzx(RegOperand{Reg: EAX}, RegOperand{Reg: AL})
	case "<=":
		cg.asm.Cmp(RegOperand{Reg: RBX}, RegOperand{Reg: RAX})
		cg.asm.Setle(RegOperand{Reg: AL})
		cg.asm.Movzx(RegOperand{Reg: EAX}, RegOperand{Reg: AL})
	case ">":
		cg.asm.Cmp(RegOperand{Reg: RBX}, RegOperand{Reg: RAX})
		cg.asm.Setg(RegOperand{Reg: AL})
		cg.asm.Movzx(RegOperand{Reg: EAX}, RegOperand{Reg: AL})
	case ">=":
		cg.asm.Cmp(RegOperand{Reg: RBX}, RegOperand{Reg: RAX})
		cg.asm.Setge(RegOperand{Reg: AL})
		cg.asm.Movzx(RegOperand{Reg: EAX}, RegOperand{Reg: AL})
	case "&&":
		cg.asm.And(RegOperand{Reg: RAX}, RegOperand{Reg: RBX})
	case "||":
		cg.asm.Or(RegOperand{Reg: RAX}, RegOperand{Reg: RBX})
	default:
		return fmt.Errorf("unsupported binary operator: %s", op)
	}
	return nil
}

// generateFloatBinaryOp generates code for float binary operations
// Assumes: XMM1 = left operand, XMM0 = right operand
// Result in XMM0
func (cg *CodeGenerator) generateFloatBinaryOp(op string) error {
	switch op {
	case "+":
		cg.asm.Addss(RegOperand{Reg: XMM1}, RegOperand{Reg: XMM0})
		cg.asm.Movss(RegOperand{Reg: XMM0}, RegOperand{Reg: XMM1})
	case "-":
		cg.asm.Subss(RegOperand{Reg: XMM1}, RegOperand{Reg: XMM0})
		cg.asm.Movss(RegOperand{Reg: XMM0}, RegOperand{Reg: XMM1})
	case "*":
		cg.asm.Mulss(RegOperand{Reg: XMM1}, RegOperand{Reg: XMM0})
		cg.asm.Movss(RegOperand{Reg: XMM0}, RegOperand{Reg: XMM1})
	case "/":
		cg.asm.Divss(RegOperand{Reg: XMM1}, RegOperand{Reg: XMM0})
		cg.asm.Movss(RegOperand{Reg: XMM0}, RegOperand{Reg: XMM1})
	case "==":
		cg.asm.Ucomiss(RegOperand{Reg: XMM1}, RegOperand{Reg: XMM0})
		cg.asm.Sete(RegOperand{Reg: AL})
		cg.asm.Movzx(RegOperand{Reg: EAX}, RegOperand{Reg: AL})
		cg.asm.Cvtsi2ss(RegOperand{Reg: XMM0}, RegOperand{Reg: EAX})
	case "!=":
		cg.asm.Ucomiss(RegOperand{Reg: XMM1}, RegOperand{Reg: XMM0})
		cg.asm.Setne(RegOperand{Reg: AL})
		cg.asm.Movzx(RegOperand{Reg: EAX}, RegOperand{Reg: AL})
		cg.asm.Cvtsi2ss(RegOperand{Reg: XMM0}, RegOperand{Reg: EAX})
	case "<":
		cg.asm.Ucomiss(RegOperand{Reg: XMM1}, RegOperand{Reg: XMM0})
		cg.asm.Setb(RegOperand{Reg: AL})
		cg.asm.Movzx(RegOperand{Reg: EAX}, RegOperand{Reg: AL})
		cg.asm.Cvtsi2ss(RegOperand{Reg: XMM0}, RegOperand{Reg: EAX})
	case "<=":
		cg.asm.Ucomiss(RegOperand{Reg: XMM1}, RegOperand{Reg: XMM0})
		cg.asm.Emit("setbe", RegOperand{Reg: AL}, nil)
		cg.asm.Movzx(RegOperand{Reg: EAX}, RegOperand{Reg: AL})
		cg.asm.Cvtsi2ss(RegOperand{Reg: XMM0}, RegOperand{Reg: EAX})
	case ">":
		cg.asm.Ucomiss(RegOperand{Reg: XMM1}, RegOperand{Reg: XMM0})
		cg.asm.Seta(RegOperand{Reg: AL})
		cg.asm.Movzx(RegOperand{Reg: EAX}, RegOperand{Reg: AL})
		cg.asm.Cvtsi2ss(RegOperand{Reg: XMM0}, RegOperand{Reg: EAX})
	case ">=":
		cg.asm.Ucomiss(RegOperand{Reg: XMM1}, RegOperand{Reg: XMM0})
		cg.asm.Emit("setae", RegOperand{Reg: AL}, nil)
		cg.asm.Movzx(RegOperand{Reg: EAX}, RegOperand{Reg: AL})
		cg.asm.Cvtsi2ss(RegOperand{Reg: XMM0}, RegOperand{Reg: EAX})
	default:
		return fmt.Errorf("unsupported float binary operator: %s", op)
	}
	return nil
}

// generateUnaryExpr generates code for unary expression
func (cg *CodeGenerator) generateUnaryExpr(expr *parser.UnaryExpr) error {
	operandType := cg.analyzer.GetExprType(expr.Operand)

	// Generate code for operand
	if err := cg.generateExpression(expr.Operand, operandType); err != nil {
		return err
	}

	// Apply operator
	switch expr.Operator {
	case "-":
		if operandType.Equals(types.FloatType) {
			// Negate float: XMM0 = -XMM0
			// Create -0.0 by setting sign bit
			cg.asm.Mov(RegOperand{Reg: EAX}, ImmOperand{Value: 0x80000000})
			cg.asm.Cvtsi2ss(RegOperand{Reg: XMM1}, RegOperand{Reg: EAX})
			cg.asm.Emit("xorps", RegOperand{Reg: XMM0}, RegOperand{Reg: XMM1})
		} else {
			// Negate integer: RAX = -RAX
			cg.asm.Neg(RegOperand{Reg: EAX})
		}
	case "!":
		if operandType.Equals(types.FloatType) {
			// Logical NOT for float: compare with 0
			cg.asm.Xor(RegOperand{Reg: EAX}, RegOperand{Reg: EAX})
			cg.asm.Cvtsi2ss(RegOperand{Reg: XMM1}, RegOperand{Reg: EAX})
			cg.asm.Ucomiss(RegOperand{Reg: XMM0}, RegOperand{Reg: XMM1})
			cg.asm.Sete(RegOperand{Reg: AL})
			cg.asm.Movzx(RegOperand{Reg: EAX}, RegOperand{Reg: AL})
			cg.asm.Cvtsi2ss(RegOperand{Reg: XMM0}, RegOperand{Reg: EAX})
		} else {
			// Logical NOT for int: RAX = (RAX == 0) ? 1 : 0
			cg.asm.Test(RegOperand{Reg: EAX}, RegOperand{Reg: EAX})
			cg.asm.Sete(RegOperand{Reg: AL})
			cg.asm.Movzx(RegOperand{Reg: EAX}, RegOperand{Reg: AL})
		}
	default:
		return fmt.Errorf("unsupported unary operator: %s", expr.Operator)
	}

	return nil
}

// generateCallExpr generates code for function call
func (cg *CodeGenerator) generateCallExpr(call *parser.CallExpr) error {
	// Get parameter registers
	paramRegs := cg.getParamRegisters()

	// Generate code for arguments and move to parameter registers
	for i, arg := range call.Arguments {
		argType := cg.analyzer.GetExprType(arg)

		// Generate argument expression
		if err := cg.generateExpression(arg, argType); err != nil {
			return err
		}

		// Move result to parameter register
		if i < len(paramRegs) {
			if argType.Equals(types.FloatType) {
				// Float argument goes to XMM register
				xmmReg := XMM0 + Register(i)
				if i > 0 {
					// If not already in XMM0, move it
					cg.asm.Movss(RegOperand{Reg: xmmReg}, RegOperand{Reg: XMM0})
				}
			} else {
				// Integer argument goes to general-purpose register
				reg := paramRegs[i]
				if reg != RAX {
					cg.asm.Mov(RegOperand{Reg: reg}, RegOperand{Reg: RAX})
				}
			}
		} else {
			// Push to stack for arguments beyond register capacity
			if argType.Equals(types.FloatType) {
				cg.asm.Sub(RegOperand{Reg: RSP}, ImmOperand{Value: 8})
				cg.asm.Movss(MemOperand{Base: RSP, Offset: 0}, RegOperand{Reg: XMM0})
			} else {
				cg.asm.Push(RegOperand{Reg: RAX})
			}
		}
	}

	// Call the function
	cg.asm.Call(call.Function)

	// Clean up stack if we pushed arguments
	if len(call.Arguments) > len(paramRegs) {
		stackCleanup := int64((len(call.Arguments) - len(paramRegs)) * 8)
		cg.asm.Add(RegOperand{Reg: RSP}, ImmOperand{Value: stackCleanup})
	}

	// Result is already in RAX or XMM0
	return nil
}
